### ISSUE TITLE
vhost domains not being added

### ISSUE THREAD

**Issue by notapatch** [notapatch/ansible-dokku#2]
TASK [dokku : domains:add bcs.io vhost domains of bcs.io] **************************************************************
fatal: [danna.bcs.io]: FAILED! => {"changed": false, "meta": {"error": "Command 'dokku --quiet domains bcs.io' returned non-zero exit status 1", "present": false}, "msg": "Command 'dokku --quiet domains bcs.io' returned non-zero exit status 1"}

Tasks

```
---
- import_role:
    name: ansible-dokku

- name: domains:add vhost domains
  dokku_domains:
    app: example.com
    domains:
      - my.example.com
    state: present

```

Notes:
If I add a domain using the workaround I can then set state as present or absent and it all works.

Work around

```
ssh to server
dokku domains:report  # see missing vhosts
dokku domains:add my-app my-domain
```
